name: chocolatine

on:
  push:
    branches-ignore:
      - " ga-ignore-"
  pull_request:
    branches-ignore:
      - " ga-ignore-"

env:
MIRROR_URL: "git@github.com:EpitechPromo2028/B-DOP-200-COT-2-2-chocolatine-folachade.capo-chichi.git"
EXECUTABLES:

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - uses: actions/checkout@v3
      - id: check_coding_style
        run: | 
          check.sh $(pwd) $(pwd)
          CODING_STYLE_ERRORS=$(pwd)/coding-style-reports.log)
          for ERRORS in $CODING_STYLE_ERRORS; do
            array=(`echo $ERRORS | sed 's/:/\n/g'`)
            echo "::error file=${array[1]#./},title=${array[3]#./} coding style errors detected: ${array[2]#./}::${array[4]#./}"
          done
          if [[ -n $CODING_STYLE_ERRORS ]]
          then
            exit 1
          else
            echo No coding style errors detected
          fi

  
  check_program_compilation:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    container: epitechcontent/epitest-docker:latest
    needs: check_coding_style
    steps:
      - name: Checkout GH repository
        uses: actions/checkout@master
        with:
          repository: ''

      - name: Compile repository
        run: |
        make
        make clean


  run_tests:
    needs: [check_program_compilation]
    name: "Run test for hero"
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest

    steps:
      - uses: actions/checkout@v3
      - id: run_tests
        run: make tests_run
        timeout-minutes: 2