name: chocolatine

on:
  push:
    branches-ignore:
      - " ga-ignore-"
  pull_request:
    branches-ignore:
      - " ga-ignore-"

env:
  MIRROR_URL: "https://github.com/EpitechPromo2028/B-DOP-200-COT-2-2-chocolatine-folachade.capo-chichi.git"
  EXECUTABLES: "mysh"

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: coding_style
        run: check.sh $(pwd) $(pwd)
        continue-on-error: false

  check_program_compilation:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest
    needs: [check_coding_style]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: construction 
        id: build
        run: make
        timeout-minutes: 2
      - name: Clear the depot
        run: make clean



